# Generated by Django 4.1.2 on 2022-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
                ('doctor', models.CharField(choices=[('Dr.Sudha Murthy', 'DR.SUDHA MURTHY'), ('Dr.Ragupathi', 'DR.RAGUPATHI'), ('Dr.Lee', 'DR.LEE')], default='', max_length=20)),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('addr1', models.CharField(max_length=20)),
                ('addr2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
