# Generated by Django 4.1.2 on 2022-12-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='doctor',
        ),
    ]
