# Generated by Django 4.1.2 on 2023-01-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP_app', '0002_remove_signupmodel_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='year',
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='photo',
            field=models.FileField(upload_to='PP_app/static'),
        ),
    ]
