# Generated by Django 4.1.3 on 2023-01-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP_app', '0003_remove_signupmodel_month_remove_signupmodel_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='doctor',
            field=models.CharField(choices=[('Dr.Sudha Murthy', 'DR.SUDHA MURTHY'), ('Dr.Ragupathi', 'DR.RAGUPATHI'), ('Dr.Lee', 'DR.LEE')], default='', max_length=20),
        ),
    ]
