# Generated by Django 4.1.3 on 2023-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP_app', '0004_signupmodel_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='newAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(choices=[('Pediatricians', 'Pediatricians'), ('Neurologists', 'Neurologists'), ('Obstetricians and gynecologists', 'Obstetricians and gynecologists'), ('General Physician', 'General Physician'), ('Cardiologists', 'Cardiologists')], default='', max_length=100)),
                ('doctor', models.CharField(choices=[('Dr.Sudha Murthy', 'DR.SUDHA MURTHY'), ('Dr.Ragupathi', 'DR.RAGUPATHI'), ('Dr.Lee', 'DR.LEE')], default='', max_length=20)),
                ('apptDate', models.DateField()),
                ('apptTime', models.TimeField()),
                ('appointment_description', models.CharField(max_length=150)),
            ],
        ),
    ]
